# old_available_features = ['INSTRUMENTALNESS', 'LOUDNESS', 'ALBUM', 'ARTISTS', 'EXPLICIT', 'ACOUSTICNESS', 'YEAR',
# 'KEY', 'NAME', 'MODE', 'DANCEABILITY', 'LIVENESS', 'VALENCE', 'TEMPO', 'SPEECHINESS', 'DURATION_mins', 'ENERGY']

available_features = ['INSTRUMENTALNESS', 'ACOUSTICNESS', 'EXPLICIT', 'YEAR', 'DANCEABILITY',
                      'KEY', 'MODE', 'VALENCE', 'DURATION (mins)', 'TEMPO', 'ENERGY']

